name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=mod

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.6

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test
